name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build_release:
    runs-on: ubuntu-latest
    name: Build and release luci-app-xray
    steps:
      - name: Build
        env:
          WORKSPACE: ${{ github.workspace }}
        uses: woniuzfb/luci-app-xray@v1
        id: build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: '*.ipk'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Done
        run: echo "Build complete - ${{ steps.build.outputs.date }}"
